version: "2"
services:
    frontend:
        build:
          context: ./frontend/
          dockerfile: Dockerfile
        image: frontend:1
        container_name: meduimApp-frontend
        restart: unless-stopped
        ports:
            - "4200:4200"
        depends_on:
            - backend
        networks:
            - meduimApp-network
    backend:
        build:
          context: ./backend/
          dockerfile: Dockerfile
        image: backend:1
        container_name: meduimApp-backend
        restart: unless-stopped
        ports:
            - "3001:3001"
        networks:
            - meduimApp-network
networks:
    DemoApp-network:
      driver: bridge